"""Build a 2024-style hardware-safe main patch.

The 2024-2025 project kept the NSO file/sections unchanged.  It wrote long
strings into verified dead NUL runs inside ``.rodata`` and changed only data
pointers that actually referenced the old string.  This port follows the
same rule for the 2026 main:

* normal strings are written in their original reserved slot;
* over-capacity strings get a UTF-8-safe prefix in that slot;
* if the original string has a real 64-bit pointer in ``.rodata``, the full
  mapped string is put in an unreferenced NUL run and only those `.rodata`
  pointer words are redirected;
* `.text`, `.data`, the NSO header, section sizes, and file length are never
  changed.

Dead-run selection is deliberately conservative: runs must be at least 64
bytes, have 32-byte guards at both ends, contain no pointer target found by
an all-byte 64-bit scan of `.rodata`/`.data`, and not cross a page used by an
ARM64 ADRP/ADR reference into `.rodata`.
"""

from __future__ import annotations

import argparse
import bisect
import json
import struct
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

from main_strings import NsoLayout


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MAIN = ROOT / "exefs" / "main"
DEFAULT_JSON = ROOT / "main_patch" / "main_strings_ko_menu_compact_patch.json"
DEFAULT_OUT = ROOT / "main_patch" / "main_hw_safe_pool"

MIN_RUN = 64
GUARD = 32


def pointer_index(source: bytes, layout: NsoLayout) -> tuple[dict[int, list[int]], np.ndarray]:
    """Index every exact 64-bit `.rodata` VA occurrence in rodata and data.

    A one-byte-stride uint64 view is intentional.  The 2026 dynamic/pointer
    tables are not all aligned to the section start; an 8-byte-stride scan
    misses valid addends.  The resulting counts are checked against the
    per-string metadata generated by the extractor.
    """
    pidx: dict[int, list[int]] = defaultdict(list)
    lo = layout.ro_mem
    hi = layout.ro_mem + layout.ro_size
    for file_off, size in (
        (layout.ro_file, layout.ro_size),
        (layout.data_file, layout.data_size),
    ):
        if size < 8:
            continue
        values = np.ndarray(
            (size - 7,), dtype="<u8", buffer=source, offset=file_off, strides=(1,)
        )
        hits = np.nonzero((values >= lo) & (values < hi))[0]
        for idx in hits.tolist():
            pidx[int(values[idx])].append(file_off + int(idx))
    return pidx, np.asarray(sorted(pidx), dtype=np.uint64)


def referenced_rodata_pages(source: bytes, layout: NsoLayout) -> set[int]:
    """Return pages touched by ARM64 ADRP/ADR references into `.rodata`."""
    if layout.text_size < 4:
        return set()
    words = np.frombuffer(
        source[layout.text_file : layout.text_file + (layout.text_size // 4) * 4],
        dtype="<u4",
    )
    pages: set[int] = set()
    ro_lo = layout.ro_mem
    ro_hi = layout.ro_mem + layout.ro_size
    for idx in np.nonzero(
        ((words & np.uint32(0x9F000000)) == np.uint32(0x90000000))
        | ((words & np.uint32(0x9F000000)) == np.uint32(0x10000000))
    )[0].tolist():
        word = int(words[idx])
        imm = (((word >> 5) & 0x7FFFF) << 2) | ((word >> 29) & 3)
        if imm & (1 << 20):
            imm -= 1 << 21
        pc = layout.text_mem + idx * 4
        if (word & 0x9F000000) == 0x90000000:
            target = ((pc >> 12) << 12) + (imm << 12)
            if ro_lo - 0x1000 <= target < ro_hi:
                pages.add(target >> 12)
        else:
            target = pc + imm
            if ro_lo <= target < ro_hi:
                pages.add(target >> 12)
    return pages


def relocation_destinations(source: bytes, layout: NsoLayout) -> tuple[set[int], list[dict]]:
    """Discover RELA/JMPREL destinations from the 2026 dynamic tag table.

    The 2026 tables are not at the MOD0 offset used by the 2024 executable,
    so locate the standard tag triplets directly.  We use this only as a
    safety fence: a `.data` pointer that the loader will overwrite must not
    be edited statically.
    """
    search_ranges = [
        (layout.ro_file, layout.ro_file + layout.ro_size),
        (layout.data_file, layout.data_file + layout.data_size),
    ]
    ranges: list[dict] = []
    destinations: set[int] = set()

    def find_tag(tag: int):
        needle = struct.pack("<Q", tag)
        for start, end in search_ranges:
            pos = source.find(needle, start, end)
            while pos >= 0:
                yield pos
                pos = source.find(needle, pos + 1, end)

    # DT_RELA=7, followed by DT_RELASZ=8 and DT_RELAENT=9.
    for pos in find_tag(7):
        if pos + 48 > len(source):
            continue
        value = struct.unpack_from("<Q", source, pos + 8)[0]
        tag_size, size = struct.unpack_from("<QQ", source, pos + 16)
        tag_ent, ent_size = struct.unpack_from("<QQ", source, pos + 32)
        if tag_size != 8 or tag_ent != 9 or ent_size != 24:
            continue
        file_off = layout.mem_to_file(value)
        if file_off is None or file_off + size > len(source) or size % ent_size:
            continue
        ranges.append({"kind": "RELA", "va": value, "file": file_off, "size": size})

    # DT_JMPREL=23, followed by DT_PLTRELSZ=2.  The entry size is the same
    # DT_RELAENT discovered above; all current 2026 entries are RELA.
    for pos in find_tag(0x17):
        if pos + 32 > len(source):
            continue
        value = struct.unpack_from("<Q", source, pos + 8)[0]
        tag_size, size = struct.unpack_from("<QQ", source, pos + 16)
        if tag_size != 2 or size % 24:
            continue
        file_off = layout.mem_to_file(value)
        if file_off is None or file_off + size > len(source):
            continue
        ranges.append({"kind": "JMPREL", "va": value, "file": file_off, "size": size})

    # Deduplicate candidates if a byte pattern happens to occur twice.
    unique = {(x["kind"], x["file"], x["size"]): x for x in ranges}
    for item in unique.values():
        for offset in range(item["file"], item["file"] + item["size"], 24):
            r_offset = struct.unpack_from("<Q", source, offset)[0]
            destinations.add(r_offset)
    return destinations, list(unique.values())


def safe_pool_runs(
    data: bytes | bytearray,
    layout: NsoLayout,
    pointer_targets: np.ndarray,
    code_pages: set[int],
    minimum_file_offset: int,
) -> list[list[int]]:
    """Find guarded NUL runs which no data/code reference can reach."""
    ro = np.frombuffer(data, dtype=np.uint8)[
        layout.ro_file : layout.ro_file + layout.ro_size
    ]
    nonzero = np.nonzero(ro != 0)[0]
    starts = np.concatenate(([0], nonzero + 1))
    ends = np.concatenate((nonzero, [layout.ro_size]))
    runs: list[list[int]] = []
    for start, end in zip(starts.tolist(), ends.tolist()):
        length = end - start
        if length < MIN_RUN:
            continue
        file_start = layout.ro_file + start + GUARD
        file_end = layout.ro_file + end - GUARD
        if file_start < minimum_file_offset or file_end - file_start < 8:
            continue
        va_start = layout.ro_mem + start
        va_end = layout.ro_mem + end
        lo = int(np.searchsorted(pointer_targets, va_start))
        hi = int(np.searchsorted(pointer_targets, va_end))
        if hi > lo:
            continue
        first_page = va_start >> 12
        last_page = (va_end - 1) >> 12
        if any(page in code_pages for page in range(first_page, last_page + 1)):
            continue
        runs.append([file_start, file_end - file_start])
    runs.sort(key=lambda item: (-item[1], item[0]))
    return runs


def safe_prefix(encoded: bytes, capacity: int) -> bytes:
    limit = max(0, capacity - 1)
    cut = encoded[:limit]
    while cut:
        try:
            cut.decode("utf-8")
            return cut
        except UnicodeDecodeError:
            cut = cut[:-1]
    return b""


def in_intervals(
    offset: int,
    intervals: list[tuple[int, int]],
    starts: list[int],
) -> bool:
    """Check an offset against sorted, non-overlapping intervals."""
    if not intervals:
        return False
    idx = bisect.bisect_right(starts, offset) - 1
    return idx >= 0 and offset < intervals[idx][1]


def patch_main_hardware_safe_pool(main_path: Path, json_path: Path, out_path: Path) -> dict:
    source = main_path.read_bytes()
    layout = NsoLayout.from_bytes(source)
    obj = json.loads(json_path.read_text(encoding="utf-8"))
    records = obj["strings"] if isinstance(obj, dict) else obj
    buf = bytearray(source)

    pidx, pointer_targets = pointer_index(source, layout)
    code_pages = referenced_rodata_pages(source, layout)
    relocation_targets, relocation_ranges = relocation_destinations(source, layout)

    total = 0
    excluded = 0
    unchanged = 0
    inplace = 0
    overflow = []
    invalid = []
    slot_intervals: list[tuple[int, int]] = []

    # First pass: preserve all original offsets.  Long strings get a clean
    # prefix; their complete bytes are handled by the guarded pool below.
    for rec in records:
        total += 1
        if (
            rec.get("patch_excluded")
            or rec.get("preserve_original")
            or rec.get("localization_target") == "no"
        ):
            excluded += 1
            continue
        try:
            off = int(rec["offset"])
            capacity = int(rec["capacity"])
            byte_length = int(rec.get("byte_length", 0))
        except (KeyError, TypeError, ValueError):
            invalid.append({"reason": "invalid_offset_or_capacity", "record": rec})
            continue
        if off < layout.ro_file or off + capacity > layout.ro_file + layout.ro_size:
            invalid.append({"offset": off, "capacity": capacity, "reason": "outside_rodata"})
            continue
        if capacity <= 0 or byte_length < 0 or byte_length > capacity:
            invalid.append({"offset": off, "capacity": capacity, "reason": "invalid_byte_length"})
            continue

        text = rec.get("game_text", rec.get("text", ""))
        try:
            encoded = str(text).encode("utf-8")
        except UnicodeEncodeError as exc:
            invalid.append({"offset": off, "reason": f"utf8:{exc}"})
            continue
        slot_intervals.append((off, off + capacity))
        original_text = source[off : off + byte_length]
        if encoded == original_text and source[off + len(encoded) : off + capacity].rstrip(b"\0") == b"":
            unchanged += 1
            continue

        needed = len(encoded) + 1
        if needed <= capacity:
            slot = encoded + b"\0"
            buf[off : off + capacity] = slot + b"\0" * (capacity - len(slot))
            inplace += 1
            continue

        prefix = safe_prefix(encoded, capacity)
        slot = prefix + b"\0"
        buf[off : off + capacity] = slot + b"\0" * (capacity - len(slot))
        overflow.append((rec, encoded, needed))

    slot_intervals.sort()
    slot_starts = [x[0] for x in slot_intervals]
    for left, right in zip(slot_intervals, slot_intervals[1:]):
        if left[1] > right[0]:
            raise AssertionError(f"overlapping string slots: {left} / {right}")

    # Build the pool after in-place writes so a newly used NUL slack region can
    # never be reused for a second purpose.
    pool_min = min((x[0] for x in slot_intervals), default=layout.ro_file)
    runs = safe_pool_runs(buf, layout, pointer_targets, code_pages, pool_min)
    safe_pool_run_count = len(runs)
    pool_total = sum(size for _, size in runs)
    allocated: list[tuple[int, int]] = []

    def alloc(need: int) -> int | None:
        for i, (pos, size) in enumerate(runs):
            if size < need:
                continue
            runs[i] = [pos + need, size - need]
            if runs[i][1] < 8:
                runs.pop(i)
            allocated.append((pos, pos + need))
            return pos
        return None

    redirected: list[dict] = []
    overflow_no_ro_pointer = 0
    overflow_pool_full = 0
    overflow_no_pointer = 0
    pointer_locations_rewritten = 0
    data_only_pointer = 0
    data_pointer_locations_rewritten = 0
    relocated_data_pointer_locations = 0
    data_rewrite_locations: set[int] = set()
    overlapping_pointer = 0

    for rec, encoded, needed in overflow:
        off = int(rec["offset"])
        target_va = layout.ro_mem + off - layout.ro_file
        locations = pidx.get(target_va, [])
        ro_locations = [
            loc
            for loc in locations
            if layout.ro_file <= loc < layout.ro_file + layout.ro_size
        ]
        data_locations = [
            loc
            for loc in locations
            if layout.data_file <= loc < layout.data_file + layout.data_size
        ]
        if not locations:
            overflow_no_pointer += 1
            continue
        ro_locations = [
            loc for loc in ro_locations if not in_intervals(loc, slot_intervals, slot_starts)
        ]
        writable_data_locations = [
            loc
            for loc in data_locations
            if layout.data_mem + loc - layout.data_file not in relocation_targets
        ]
        relocated_data_pointer_locations += len(data_locations) - len(writable_data_locations)
        writable_locations = ro_locations + writable_data_locations
        if not writable_locations:
            if data_locations:
                data_only_pointer += 1
            else:
                overlapping_pointer += 1
            overflow_no_ro_pointer += 1
            continue
        pos = alloc(needed)
        if pos is None:
            overflow_pool_full += 1
            continue
        # The candidate was all-zero before allocation and after the in-place
        # pass; keep this assertion close to the write for easy diagnosis.
        if any(source[pos + i] != 0 or buf[pos + i] != 0 for i in range(needed)):
            raise AssertionError(f"non-zero pool allocation at 0x{pos:x}")
        new_file = pos
        new_va = layout.ro_mem + (pos - layout.ro_file)
        buf[pos : pos + len(encoded)] = encoded
        buf[pos + len(encoded)] = 0
        for loc in writable_locations:
            struct.pack_into("<Q", buf, loc, new_va)
        pointer_locations_rewritten += len(writable_locations)
        data_pointer_locations_rewritten += len(writable_data_locations)
        data_rewrite_locations.update(writable_data_locations)
        redirected.append(
            {
                "offset": off,
                "new_file": new_file,
                "new_mem": new_va,
                "bytes": len(encoded) + 1,
                "ro_pointer_locations": len(ro_locations),
                "data_pointer_locations_rewritten": len(writable_data_locations),
                "data_pointer_locations_unchanged": len(data_locations) - len(writable_data_locations),
                "source": rec.get("text"),
                "korean": rec.get("korean"),
            }
        )

    # Structural validation.  No pointer outside the allowed rodata words,
    # no section/header change, and every redirected string is complete.
    if len(buf) != len(source):
        raise AssertionError("output size changed")
    if buf[:0x100] != source[:0x100]:
        raise AssertionError("NSO header changed")
    if buf[layout.text_file : layout.text_file + layout.text_size] != source[
        layout.text_file : layout.text_file + layout.text_size
    ]:
        raise AssertionError(".text changed")
    # Unlike the 2024 binary, this update stores many static string-table
    # pointers in .data.  They are safe to change only at the exact words
    # selected above; relocation destinations were filtered out.
    data_arr_before = np.frombuffer(
        source[layout.data_file : layout.data_file + layout.data_size], dtype=np.uint8
    )
    data_arr_after = np.frombuffer(
        buf[layout.data_file : layout.data_file + layout.data_size], dtype=np.uint8
    )
    data_diff = np.nonzero(data_arr_before != data_arr_after)[0]
    data_allowed = np.zeros(layout.data_size, dtype=np.bool_)
    for loc in data_rewrite_locations:
        rel = loc - layout.data_file
        data_allowed[rel : rel + 8] = True
    if len(data_diff) and np.any(~data_allowed[data_diff]):
        bad_data = data_diff[~data_allowed[data_diff]]
        raise AssertionError(f"unexpected .data changes: {len(bad_data)} at {bad_data[:8].tolist()}")
    for left, right in allocated:
        if source[left:right].count(0) != right - left:
            raise AssertionError(f"pool was not original NUL at 0x{left:x}")

    # Confirm the exact bytes and pointer values for all redirects.
    overflow_by_offset = {
        int(rec["offset"]): (rec, encoded, needed)
        for rec, encoded, needed in overflow
    }
    for item in redirected:
        old_off = item["offset"]
        new_file = item["new_file"]
        rec, encoded, _ = overflow_by_offset[old_off]
        if source[new_file : new_file + len(encoded) + 1] != b"\0" * (len(encoded) + 1):
            raise AssertionError("pool source bytes were not zero")
        if buf[new_file : new_file + len(encoded)] != encoded or buf[new_file + len(encoded)] != 0:
            raise AssertionError("redirected string bytes mismatch")
        target_va = layout.ro_mem + old_off - layout.ro_file
        new_va = item["new_mem"]
        for loc in pidx[target_va]:
            is_ro = layout.ro_file <= loc < layout.ro_file + layout.ro_size
            is_data = layout.data_file <= loc < layout.data_file + layout.data_size
            writable_data = is_data and layout.data_mem + loc - layout.data_file not in relocation_targets
            if (is_ro and not in_intervals(loc, slot_intervals, slot_starts)) or writable_data:
                if struct.unpack_from("<Q", buf, loc)[0] != new_va:
                    raise AssertionError("redirected pointer mismatch")

    # Detect accidental changes outside original slots, pool allocations, and
    # explicitly rewritten rodata pointers.
    original_arr = np.frombuffer(source, dtype=np.uint8)
    output_arr = np.frombuffer(buf, dtype=np.uint8)
    diff = np.nonzero(original_arr != output_arr)[0]
    allowed = np.zeros(len(source), dtype=np.bool_)
    for left, right in slot_intervals:
        allowed[left:right] = True
    for left, right in allocated:
        allowed[left:right] = True
    for rec in redirected:
        target_va = layout.ro_mem + rec["offset"] - layout.ro_file
        for loc in pidx[target_va]:
            is_ro = layout.ro_file <= loc < layout.ro_file + layout.ro_size
            is_data = layout.data_file <= loc < layout.data_file + layout.data_size
            writable_data = is_data and layout.data_mem + loc - layout.data_file not in relocation_targets
            if is_ro or writable_data:
                allowed[loc : loc + 8] = True
    violations = diff[~allowed[diff]]
    if len(violations):
        raise AssertionError(f"unexpected changes: {len(violations)} at {violations[:8].tolist()}")

    report = {
        "format": 1,
        "mode": "2024_style_dead_zero_run_rodata_redirect",
        "input": str(main_path),
        "output": str(out_path),
        "json": str(json_path),
        "input_size": len(source),
        "output_size": len(buf),
        "layout_unchanged": True,
        "text_header_unchanged": True,
        "data_changed_pointer_words_only": True,
        "records_total": total,
        "preserve_original_skipped": excluded,
        "unchanged": unchanged,
        "inplace": inplace,
        "overflow_total": len(overflow),
        "redirected_full_strings": len(redirected),
        "overflow_no_pointer": overflow_no_pointer,
        "overflow_no_ro_pointer": overflow_no_ro_pointer,
        "overflow_data_only_pointer": data_only_pointer,
        "overflow_overlapping_pointer": overlapping_pointer,
        "overflow_pool_full": overflow_pool_full,
        "pointer_locations_rewritten": pointer_locations_rewritten,
        "data_pointer_locations_rewritten": data_pointer_locations_rewritten,
        "relocated_data_pointer_locations_unchanged": relocated_data_pointer_locations,
        "relocation_ranges": relocation_ranges,
        "pointer_targets_total": len(pointer_targets),
        "pointer_locations_total": sum(len(v) for v in pidx.values()),
        "code_rodata_pages_excluded": len(code_pages),
        "safe_pool_runs_before_alloc": safe_pool_run_count,
        "safe_pool_bytes_before_alloc": pool_total,
        "safe_pool_bytes_allocated": sum(right - left for left, right in allocated),
        "allocated_ranges": [[left, right] for left, right in allocated],
        "redirected_records": redirected,
        "invalid_records": invalid,
        "diff_bytes": int(len(diff)),
        "diff_first_last": [int(diff[0]), int(diff[-1])] if len(diff) else None,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(buf)
    report_path = out_path.with_suffix(out_path.suffix + ".report.json")
    report_path.write_text(json.dumps(report, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    return report


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--main", type=Path, default=DEFAULT_MAIN)
    ap.add_argument("--json", type=Path, default=DEFAULT_JSON)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    report = patch_main_hardware_safe_pool(args.main, args.json, args.out)
    print(json.dumps({k: v for k, v in report.items() if k not in ("allocated_ranges", "redirected_records", "invalid_records")}, ensure_ascii=False))


if __name__ == "__main__":
    main()
